services:
  file_storage:
    container_name: file_storage
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${FILE_STORAGE_USER}
      - MINIO_ROOT_PASSWORD=${FILE_STORAGE_PASSWORD}
      - MINIO_BUCKET=${FILE_STORAGE_BUCKET}
    command: server /data --console-address ":9001"
    ports:
      - "${FILE_STORAGE_PORT_PUBLIC}:${FILE_STORAGE_PORT_PRIVATE}"
      - "9001:9001"
    volumes:
      - file_storage_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "${FILE_STORAGE_INTERNAL_ENDPOINT}/minio/health/live" ]
      interval: 1s
      timeout: 5s
      retries: 5

  database:
    container_name: database
    image: pgvector/pgvector:pg18
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DATABASE_PORT_PUBLIC:-5432}:${DATABASE_PORT_PRIVATE:-5432}"
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      - file_storage

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/app
      - api_venv:/app/.venv
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT_PUBLIC:-5173}:${FRONTEND_PORT_PRIVATE:-5173}"
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    depends_on:
      - api

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    ports:
      - "${NODE_EXPORTER_PORT_PUBLIC:-9100}:${NODE_EXPORTER_PORT_PRIVATE:-9100}"
    depends_on:
      - api

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT_PUBLIC:-9090}:${PROMETHEUS_PORT_PRIVATE:-9090}"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      - node-exporter

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT_PRIVATE:-3000}:${GRAFANA_PORT_PUBLIC:-3000}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - prometheus

volumes:
  api_venv:
  database_data:
  file_storage_data:
  prometheus_data:
