"""edit memoryspace model

Revision ID: 1cf67cd99bde
Revises: 9c599b91bcc8
Create Date: 2026-08-25 17:01:05.532543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1cf67cd99bde'
down_revision: Union[str, Sequence[str], None] = '9c599b91bcc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memoryspace', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memoryspace', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memoryspace', 'description')
    op.drop_column('memoryspace', 'name')
    # ### end Alembic commands ###
