"""update user and refresh token

Revision ID: 3fefed27f435
Revises: 144fb55ce8f9
Create Date: 2026-08-13 08:13:16.755307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3fefed27f435'
down_revision: Union[str, Sequence[str], None] = '144fb55ce8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('refreshtoken', sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False)
    op.create_foreign_key(None, 'refreshtoken', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('refreshtoken', 'token_hashed')
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'name')
    op.add_column('refreshtoken', sa.Column('token_hashed', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refreshtoken', type_='foreignkey')
    op.drop_index(op.f('ix_refreshtoken_user_id'), table_name='refreshtoken')
    op.drop_column('refreshtoken', 'token')
    op.drop_column('refreshtoken', 'user_id')
    # ### end Alembic commands ###
